---
title: "1940 Data"
---

# 1940 Data

This will be the basic data pre-processing work for Phoenix, Arizona. The other city notebooks follow the same steps but with different sets of CBSA data.

Estimated time to run: a few minutes

Load packages:

```{r}
library(readr) # Read Rectangular Text Data
library(ggplot2) # Create Elegant Data Visualisations Using the Grammar of Graphics
library(glue) # Interpreted String Literals
library(here) # A Simpler Way to Find Your Files
library(sf) # Simple Features for R
library(tidycensus) # Load US Census Boundary and Attribute Data as 'tidyverse' and 'sf'-Ready Data Frames
library(tidyverse) # Easily Install and Load the 'Tidyverse'
library(tigris) # Load Census TIGER/Line Shapefiles
```

```{r}
us_1940_demo <- read_csv(glue(here::here(),
                               "/data-raw/1940-data/nhgis0001_csv/nhgis0001_ds76_1940_tract.csv"))

us_1940_tract <- st_read(glue(here::here(),
                               "/data-raw/1940-data/nhgis0001_shape/nhgis0001_shapefile_tl2000_us_tract_1940/US_tract_1940.shp"))
```

```{r load files part 1}
# Tracts
load(file = glue::glue(here::here(),
                       "/data/houston_tracts.rda"))

# Urban boundaries
load(file = glue::glue(here::here(),
                       "/data/houston_urban.rda"))

# CBSA boundary
load(file = glue::glue(here::here(),
                       "/data/houston_cbsa.rda"))

# Walksheds
load(file = glue::glue(here::here(),
                       "/data/houston_walksheds.rda"))
```

```{r}
ggplot() +
  geom_sf(data = us_1940_tract) +
  theme_minimal()
```

```{r}
houston_1940_tracts <- houston_cbsa |>
  st_filter(us_1940_tract, 
            .predicate = st_intersects)
```


