---
title: "00-Complete-Census-Data"
---

# Setup

```{r}
library(tidycensus)
library(tigris)
library(dplyr) # A Grammar of Data Manipulation
library(ggraph) # An Implementation of Grammar of Graphics for Graphs and Networks
library(ggplot2) # Create Elegant Data Visualisations Using the Grammar of Graphics
library(glue) # Interpreted String Literals
library(here) # A Simpler Way to Find Your Files
library(igraph) # Network Analysis and Visualization
library(sf) # Simple Features for R
library(tidygraph) # A Tidy API for Graph Manipulation
library(tidyr) # Tidy Messy Data
library(purrr) # Functional Programming Tools
library(units) # Measurement Units for R Vectors
library(ggpubr)
# library(vioplot)
# library(devtools)
# library(introdataviz)
```

```{r}
load(file = glue::glue(here::here(),
                       "/data/houston_tracts_df.rda"))

load(file = glue::glue(here::here(),
                       "/data/atlanta_tracts_df.rda"))

load(file = glue::glue(here::here(),
                       "/data/phoenix_tracts_df.rda"))

load(file = glue::glue(here::here(),
                       "/data/nashville_tracts_df.rda"))

load(file = glue::glue(here::here(),
                       "/data/jacksonville_tracts_df.rda"))
```

```{r}
combined_df <- rbind(houston_tracts_df, atlanta_tracts_df, phoenix_tracts_df, nashville_tracts_df, jacksonville_tracts_df)
```


```{r}
save(combined_df, 
     file = glue::glue(here::here(),
                       "/data/combined_df.rda"),
     compress = "bzip2")
```

# Graphs

```{r scatterplot of black prop}
ggscatter(combined_df, x = "black_prop", y = "area", add = "reg.line", shape = 19, size = 0.5, xlab = "Proportion of Black Population in Census Tract", ylab = "Area of Walkshed in Square Meters", font.label = c(5, "plain", "black")) +
  stat_cor(label.x = 0.75, label.y = 2000000) #label placement
```

```{r scatterplot of white prop}
ggscatter(combined_df, x = "white_prop", y = "area", add = "reg.line", shape = 19, size = 0.5, xlab = "Proportion of White Population in Census Tract", ylab = "Area of Walkshed in Square Meters", font.label = c(5, "plain", "black")) +
  stat_cor(label.x = 0.75, label.y = 2000000) #label placement
```

```{r scatterplot of income}
ggscatter(combined_df, x = "income", y = "area", add = "reg.line", shape = 19, size = 0.5, xlab = "Average Household Income in Census Tract", ylab = "Area of Walkshed in Square Meters", xlim = c(0, 155000)) +
  stat_cor(label.x = 110000, label.y = 2000000) #label placement
```

